version: "3.7"
services:
    host:
        build:
            context: .
            dockerfile: analytics.Dockerfile
        ports:
            - 8083:80
        volumes:
            - ./:/var/www/html
        environment:
            OWA_PUBLIC_URL: http://localhost:8083/
            OWA_DB_NAME: owa
            OWA_DB_HOST: database
            OWA_DB_USER: mack
            OWA_DB_PASSWORD: Kllo555
        depends_on:
            - database
        networks:
            db:
    database:
        image: mysql:8.0.20
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - /var/lib/mysql
            # - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
        environment:
            MYSQL_ROOT_PASSWORD: Kllo555
            MYSQL_DATABASE: owa
            MYSQL_USER: mack
            MYSQL_PASSWORD: Kllo555
        networks:
            db:
                aliases:
                    - database

networks:
    db: